services:
  Tardigrades\SectionField\Service\DoctrineApplicationManager:
    autowire: false
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
      $languageManager: '@Tardigrades\SectionField\Service\DoctrineLanguageManager'

  section_field.manager.doctrine.application_manager: '@Tardigrades\SectionField\Service\DoctrineApplicationManager'

  Tardigrades\SectionField\Service\DoctrineLanguageManager:
    autowire: false
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  section_field.manager.doctrine.language_manager: '@Tardigrades\SectionField\Service\DoctrineLanguageManager'

  Tardigrades\SectionField\Service\DoctrineSectionManager:
    autowire: false
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
      $fieldManager: '@Tardigrades\SectionField\Service\DoctrineFieldManager'
      $sectionHistoryManager: '@Tardigrades\SectionField\Service\DoctrineSectionHistoryManager'

  section_field.manager.doctrine.section_manager: '@Tardigrades\SectionField\Service\DoctrineSectionManager'

  Tardigrades\SectionField\Service\DoctrineSectionHistoryManager:
    autowire: false
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  section_field.manager.doctrine.section_history_manager: '@Tardigrades\SectionField\Service\DoctrineSectionHistoryManager'

  Tardigrades\SectionField\Service\DoctrineFieldTypeManager:
    autowire: false
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  section_field.manager.doctrine.field_type_manager: '@Tardigrades\SectionField\Service\DoctrineFieldTypeManager'

  Tardigrades\SectionField\Service\DoctrineFieldManager:
    autowire: false
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
      $fieldTypeManager: '@Tardigrades\SectionField\Service\DoctrineFieldTypeManager'

  section_field.manager.doctrine.field_manager: '@Tardigrades\SectionField\Service\DoctrineFieldManager'

  Tardigrades\Twig\SectionTwigExtension:
    autowire: false
    arguments:
      - '@section_field.read.section'
    tags: [twig.extension]

  section_field.twig.section: '@Tardigrades\Twig\SectionTwigExtension'

  # override this service with true as the second parameter to enable caching
  # at this point caching is for GET calls on the REST Api (sexy-field-api)
  Tardigrades\SectionField\Service\DefaultCache:
    public: false
    arguments:
      - '@Symfony\Component\Cache\Adapter\TagAwareAdapter'
      - false

  default.cache: '@Tardigrades\SectionField\Service\DefaultCache'

  Symfony\Component\Cache\Adapter\PdoAdapter:
    public: false
    arguments:
      - '@doctrine.dbal.default_connection'

  Symfony\Component\Cache\Adapter\TagAwareAdapter:
    public: false
    arguments:
      - '@Symfony\Component\Cache\Adapter\PdoAdapter'


